### ISSUE TITLE
Don't use while (true)

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-NokKbl#2]
Consider using boolean result returned from `game.guess(number)` to determine when to stop the loop.

https://github.com/OOP2018/guessing-game-NokKbl/blob/0e74e0cb543a16e6f194969bf8f0728544645eac/src/GameSolver.java#L22-L30

**Comment by NokKbl** [comment]
I already fixed it but can I ask why I can't use while(true) and better to use the boolean result from game.guess(number)?? I just want to know why. Thank you! :)
